// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackAndGo.Infrastructure.Persistence;

#nullable disable

namespace PackAndGo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240830153250_AddPackingLists")]
    partial class AddPackingLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PackAndGo.Infrastructure.DataModels.ItemDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPacked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PackingListDataModelId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackingListDataModelId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PackAndGo.Infrastructure.DataModels.PackingListDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PackingLists");
                });

            modelBuilder.Entity("PackAndGo.Infrastructure.DataModels.UserDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("097498c7-66ad-4a1f-b1a4-0843e89a78e2"),
                            Email = "john.doe@test.com"
                        },
                        new
                        {
                            Id = new Guid("0c0e1af3-d9aa-4b86-a41b-fb44cdb685a4"),
                            Email = "jane.doe@test.com"
                        },
                        new
                        {
                            Id = new Guid("5458a1ce-d74f-42d8-b83d-b917cc21a8f9"),
                            Email = "jacob.doe@test.com"
                        });
                });

            modelBuilder.Entity("PackAndGo.Infrastructure.DataModels.ItemDataModel", b =>
                {
                    b.HasOne("PackAndGo.Infrastructure.DataModels.PackingListDataModel", null)
                        .WithMany("Items")
                        .HasForeignKey("PackingListDataModelId");
                });

            modelBuilder.Entity("PackAndGo.Infrastructure.DataModels.PackingListDataModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
