// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackAndGo.Infrastructure.Persistence;

#nullable disable

namespace PackAndGo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PackAndGo.Infrastructure.DataModels.UserDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51181cb1-4e76-4402-aee6-aac3405ca654"),
                            Email = "john.doe@test.com"
                        },
                        new
                        {
                            Id = new Guid("2fc56300-17dd-4a48-9793-363f14f29a30"),
                            Email = "jane.doe@test.com"
                        },
                        new
                        {
                            Id = new Guid("8a468c35-db94-4e17-ae84-a7b25f581e8f"),
                            Email = "jacob.doe@test.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
